# Generated by Django 5.0.1 on 2024-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraloffer',
            name='limit',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
