# Generated by Django 4.2.7 on 2024-02-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional_product_image',
            name='product',
        ),
        migrations.AddField(
            model_name='additional_product_image',
            name='product_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_images', to='store.product_variant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additional_product_image',
            name='image',
            field=models.ImageField(upload_to='media/photos/additional_photos'),
        ),
    ]
