# Generated by Django 4.2.7 on 2024-02-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_attribute_value_attribute_delete_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_value',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
