# Generated by Django 4.2.7 on 2024-02-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_attribute_value_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product_variant',
            name='Unique skuid must be provided',
        ),
    ]
