# Generated by Django 4.2.7 on 2024-02-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_variant_unique_skuid_must_be_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='sku_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
