# Generated by Django 4.2.7 on 2024-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_variant_sku_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='thumbnail_image',
            field=models.ImageField(upload_to='media/photos/product_variant/'),
        ),
    ]
