# Generated by Django 5.0.1 on 2024-03-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_coupon_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='total_coupons',
            field=models.IntegerField(default=0),
        ),
    ]
