# Generated by Django 5.0.1 on 2024-03-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='store.product_variant'),
        ),
    ]
