# Generated by Django 5.0.1 on 2024-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_coupon_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='usage_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
