# Generated by Django 5.0.1 on 2024-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_usercoupon_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
