# Generated by Django 5.0.1 on 2024-03-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20240318_1630'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product_variant',
        #     name='offer_price',
        # ),
    ]
