# Generated by Django 5.0.1 on 2024-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20240318_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
