# Generated by Django 5.0.1 on 2024-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_variant_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='media/photos/banner')),
                ('is_visible', models.BooleanField(default=True)),
                ('banner_title', models.CharField(max_length=100)),
            ],
        ),
    ]
