# Generated by Django 5.0.1 on 2024-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_banner_banner_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/photos/banner_videos/'),
        ),
    ]
