# Generated by Django 5.0.1 on 2024-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/banner'),
        ),
    ]
