# Generated by Django 5.0.1 on 2024-03-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_alter_user_date_of_birth_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(null=True, upload_to='media/photos/userphotos'),
        ),
    ]
