# Generated by Django 5.0.1 on 2024-03-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cart_coupon'),
        ('store', '0023_product_variant_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon_applied',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
    ]
