# Generated by Django 5.0.1 on 2024-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_cartitem_coupon_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
    ]
