# Generated by Django 5.0.1 on 2024-03-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_remove_cartitem_coupon_applied_and_more'),
        ('store', '0023_product_variant_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_applied',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
    ]
