# Generated by Django 5.0.1 on 2024-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_cart_coupon_applied_cart_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_total',
            field=models.IntegerField(default=0),
        ),
    ]
