# Generated by Django 5.0.1 on 2024-03-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_cart_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total',
        ),
    ]
