# Generated by Django 4.2.7 on 2024-02-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user_image',
            field=models.ImageField(null=True, upload_to='photos/user_images'),
        ),
    ]
