# Generated by Django 4.2.7 on 2024-02-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_address_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
