# Generated by Django 4.2.7 on 2024-02-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_address_street_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_image',
        ),
    ]
