# Generated by Django 4.2.7 on 2024-02-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_address_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_image',
        ),
    ]
