# Generated by Django 5.0.1 on 2024-03-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
