# Generated by Django 5.0.1 on 2024-03-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
