# Generated by Django 5.0.1 on 2024-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_grandtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
