# Generated by Django 5.0.1 on 2024-03-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
